config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  post "/orders/delivered/:id" => "orders#delivered", as: :order_delivered
  get "/change_menu" => "menus#change_menu", as: :change_menus
  get "/change_menu_items" => "menus#change_menu_items", as: :change_menus_items
  get "/create_all_orders" => "order_items#create_all_orders", as: :create_all_orders
  get "/fetch_data" => "sales#fetch_data", as: :fetch_data
  resources :menu_items, :menus, :orders, :order_items, :checkouts, :cart_items, :sales

  get "/signup" => "users#new", as: :new_users
  post "/signup" => "users#create", as: :users
  
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  get "/confirm" => "orders#confirm", as: :confirm_order
  get "/sessions/update" => "sessions#update", as: :update_session

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :menu_items
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def change_menu
    @page = "Modify menu"
    @menus = Menu.all
    current_user

    render "index"
  end

  def change_menu_items
    @page = "Modify menu items"
    @menus = Menu.all
    current_user
    @options = []
    @menus.each do |menu|
      @options << [menu.name, menu.id]
    end

    render "index"
  end

  def index
    @page = "Menu"
    @menus = Menu.all
    current_user
    @cartitems = @current_user.cart_items

    render "index"
  end

  def create
    name = params[:name]
    menu = Menu.new(
      name: name
    )

    if menu.save
      flash[:success] = "Menu #{name} is created"
      redirect_to change_menus_path
    else
      flash[:error] = "Error while creating menu"
      redirect_to change_menus_path
    end
  end

  def destroy
    id = params[:id]
    menu = Menu.find(id)
    menuitems = menu.menu_items
    menuitems.destroy_all
    menu.destroy
    redirect_to change_menus_path
  end

end

app/views/menus/_menu-section.html.erb
<div class = "menu-section">
  <div class = "heading-and-form">
    <h3><%= heading %></h3>
    
    <% if(@page == "Modify menu") %>
      <%= form_with url: "/menus/#{id}", class: "deletemenu-form", method: "delete" do |form| %>
        <%= form.submit "Delete", 
          class: "menu-delete-btn"
        %>
      <% end %>
    <% end %>
  </div>

  <% if @page != "Modify menu" %>
    <ul>
      <% menuitems.each do |menuitem| %>
        <li class = "item">
          <p class = "item-name"> <%= menuitem.name %> </p>
          <div class = "item-image">
            <% if menuitem.avatar.attached? %>
              <%= image_tag(url_for(menuitem.avatar)) %>
            <% end %>
          </div>
          <p class = "item-desc"> <%= menuitem.description %> </p>
          <p class = "item-price"> <i class="fas fa-rupee-sign"></i> <%= menuitem.price %> </p>

          <div class = "item-buttons">
            <% if @current_user.role == "Owner" && @page == "Modify menu items" %>
              <%= form_with url: "/menu_items/#{menuitem.id}", method: "delete" do |form| %>
                <%= form.submit "Delete", 
                  class: "menuitem-btn menuitem-delete-btn"
                %>
              <% end %>
            <% end %>

            <% if @current_user.role != "Billing clerk" && @page == "Menu" %>
              <%= form_with url: cart_items_path do |form| %>
                <%= form.hidden_field :menu_item_id, value: menuitem.id %>
                <%= form.number_field :quantity, placeholder: "Quantity" %>
                <%= form.submit "Add", class: "menuitem-btn" %>
              <% end %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
    
  <% end %>
</div>

app/views/menus/index.html.erb
<% if(flash[:error]) %>
  <div class = "error-msg flash-message">
    <%= flash[:error] %>
  </div>
<% end %>

<% if(flash[:success]) %>
  <div class = "success-msg flash-message">
    <%= flash[:success] %>
  </div>
<% end %>

<div class = "menu">
  <div class = "main-section">
    <div class = "main-section-heading">
      <h2>Menu</h2>
    </div>
    
    <% if @current_user.role == "Owner" && @page == "Modify menu" %>
      <%= form_with url: menus_path, class: "add-menu" do |form| %>
        <%= form.text_field :name, placeholder: "Name" %>
        <%= form.submit "Add" %>
      <% end %>
    <% end %>
    
    <% if @current_user.role == "Owner" && @page == "Modify menu items" %>
      <%= form_with url: menu_items_path, class: "add-item" do |form| %>
        <div class = "first-row">
          <%= form.text_field :name, placeholder: "Name" %>
          <%= form.number_field :price, placeholder: "Price" %>
          <%= form.select :menu_id, @options %>
        </div>

        <div class = "second-row">
          <%= form.text_area :description, placeholder: "Description" %>
        </div>

        <div class = "third-row">
        <label for="avatar"> MenuItem image </label>
        <%= form.file_field :avatar, class: 'form-control', direct_upload: true  %>
        <%= form.submit "Add" %>
        </div>
      <% end %>
    <% end %>

    <div class = "menu-sections">
        <% @menus.each do |menu| %>
          <%= render partial: "menu-section", locals:{
            heading: menu.name,
            id: menu.id,
            menuitems: menu.menu_items
          } %>
        <% end %>
    </div>
  </div>

  <% if @cartitems && @cartitems.count > 0 %>
    <div class = "added-items" >
      <div class = "inside-added-items" > 
        <h3> Cart </h3>

        <div class = "cartitems-container">
          <ul>
            <% @cartitems.each do |cartitem| %>
              <% @menuitem = cartitem.cartitem_info(cartitem.menu_item_id) %>
              <li>
                <div class = "order-item-name"> <%= @menuitem.name %> </div>
                <div class = "priceAndButton">
                  <p><i class="fas fa-rupee-sign"></i> <%= @menuitem.price %>  * <%= cartitem.quantity %> </p>
                  <%= form_with url: "/cart_items/#{cartitem.id}", method: "delete" do |form| %>
                    <%= form.submit "Remove", class: "remove-orderitem" %>
                  <% end %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>

        <div class = "buttons">
          <div class = "checkout-container">
            <%= form_with url: orders_path, method: "post" do |form| %>
              <%= form.submit "Checkout", 
                class: "checkout-btn",
                disabled: @cartitems.count == 0
              %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>