config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  post "/orders/delivered/:id" => "orders#delivered", as: :order_delivered
  get "/change_menu" => "menus#change_menu", as: :change_menus
  get "/change_menu_items" => "menus#change_menu_items", as: :change_menus_items
  get "/create_all_orders" => "order_items#create_all_orders", as: :create_all_orders
  get "/fetch_data" => "sales#fetch_data", as: :fetch_data
  resources :menu_items, :menus, :orders, :order_items, :checkouts, :cart_items, :sales

  get "/signup" => "users#new", as: :new_users
  post "/signup" => "users#create", as: :users
  
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  get "/confirm" => "orders#confirm", as: :confirm_order
  get "/sessions/update" => "sessions#update", as: :update_session

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items
  belongs_to :user

  def getUserName(user_id)
    user = User.find(user_id)
    user.name
  end

  def self.pending_orders
    where(delivered: false)
  end

  def self.delivered_orders
    where(delivered: true)
  end

  def self.pending_orders_for(user)
    pending_orders.where(user: user)
  end

  def self.delivered_orders_for(user)
    delivered_orders.where(user: user)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :ensure_user_logged_in

  def get_orders
    current_user
    if @current_user.role == "User"
      @pending_orders = Order.pending_orders_for(@current_user)
      @delivered_orders = Order.delivered_orders_for(@current_user)
      @page = "My orders"
    else
      @pending_orders = Order.pending_orders
      @delivered_orders = Order.delivered_orders
      @page = "All orders"
    end
  end

  def delivered
    id = params[:id]
    order = Order.find(id)
    order.delivered = true
    order.delivered_on = Time.now.in_time_zone("New Delhi")
    order.save()
    redirect_to orders_path
  end

  def index
    get_orders
    render "index"
  end

  def create
    current_user
    user_id = @current_user.id
    order = Order.new(
      date: Time.now,
      user_id: user_id,
      delivered: false,
      total_amount: 0
    )

    if order.save
      session[:order_id] = order.id
      redirect_to create_all_orders_path
    else
      flash[:error] = "some error occurred while creating order"
      redirect_to menus_path
    end
  end

  def confirm
    @page = "Confirm order"
    render "confirm"
  end

  def destroy
    @order = Order.find(session[:order_id])
    @orderitems = @order.order_items
    @orderitems.destroy_all
    @order.destroy

    session[:order_id] = nil
    current_order = nil
    redirect_to menus_path
  end
end

app/views/orders/confirm.html.erb
<div class = "confirm-order">
  <div class = "order-received">
    <i class="far fa-check-circle"></i>
    We have received your order
  </div>  

  <div class = "buttons">
    <%= form_with url: destroy_session_path, method: "delete" do |form| %>
      <%= button_tag type: 'submit' do %>
        Log out
      <% end %>
    <% end %>
    
    <%= form_with url: update_session_path, method: "get" do |form| %>
      <%= button_tag type: 'submit' do %>
        Return to dashboard
      <% end %>
    <% end %>
  <div>
</div>

app/views/orders/index.html.erb
<div class = "orders-list">

  <div class = "pending-orders">
    <h2> Pending </h2>
    <% if @pending_orders.count > 0 %>
      <div class = "orders">
        <table>
          <thead>
            <tr>
              <th> Order id </th>
              <% if @current_user.role == "Owner" %>
                <th> Customer Name </th>
              <% end %>
              <th> Ordered on </th>
              <th> Invoice </th>
              <% if @current_user.role == "Owner" %>
                <th> Mark as delievered </th>
              <% end %>
            </tr>
          </thead>
          
          <tbody>
            <% @pending_orders.each do |order| %>
              <tr>
                <td> <%= order.id %> </td>
                <% if @current_user.role == "Owner" %>
                  <td> <%= order.getUserName(order.user_id) %> </td>
                <% end %>
                <td> <%=  order.date %></td>

                <td>
                  <%= form_with url: checkouts_path, method: "get" do |form| %>
                    <%= form.hidden_field :order_id, value: order.id %>
                    <%= form.submit "Invoice", 
                      class: "order-deliver-btn"
                    %>
                  <% end %>
                </td>

                <% if @current_user.role == "Owner" %>
                  <td>
                    <%= form_with url: "/orders/delivered/#{order.id}" do |form| %>
                      <%= form.submit "Delivered", 
                        class: "order-deliver-btn"
                      %>
                    <% end %>
                  </td>
                <% end %>

              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>

  <div class = "delivered-orders">
    <h2> Delivered </h2>
    
    <% if @delivered_orders.count > 0 %>
      <div class = "orders">
        <table>
          <thead>
            <tr>
              <th> Order id </th>
              <% if @current_user.role == "Owner" %>
                <th> Customer Name </th>
              <% end %>
              <th> Ordered on </th>
              <th> Delivered on </th>
              <th> Invoice </th>
            </tr>
          </thead>
          
          <tbody>
            <% @delivered_orders.each do |order| %>
              <tr>
                <td> <%= order.id %> </td>
                <% if @current_user.role == "Owner" %>
                  <td> <%= order.getUserName(order.user_id) %> </td>
                <% end %>
                <td> <%=  order.date %></td>
                <td> <%=  order.delivered_on %></td>

                <td>
                  <%= form_with url: checkouts_path, method: "get" do |form| %>
                    <%= form.hidden_field :order_id, value: order.id %>
                    <%= form.submit "Invoice", 
                      class: "order-deliver-btn"
                    %>
                  <% end %>
                </td>
                
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% end %>

  </div>

</div>