config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  post "/orders/delivered/:id" => "orders#delivered", as: :order_delivered
  get "/change_menu" => "menus#change_menu", as: :change_menus
  get "/change_menu_items" => "menus#change_menu_items", as: :change_menus_items
  get "/create_all_orders" => "order_items#create_all_orders", as: :create_all_orders
  get "/fetch_data" => "sales#fetch_data", as: :fetch_data
  resources :menu_items, :menus, :orders, :order_items, :checkouts, :cart_items, :sales

  get "/signup" => "users#new", as: :new_users
  post "/signup" => "users#create", as: :users
  
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  get "/confirm" => "orders#confirm", as: :confirm_order
  get "/sessions/update" => "sessions#update", as: :update_session

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @orders = Order.all
    @total_orders = @orders.count
    @page = "Sales"
    render "index"
  end

  def fetch_data
    @contains_data = true
    array = params["starting_date"].split("-", -1)
    start = Date.new(array[0].to_i, array[1].to_i, array[2].to_i)
    array = params["ending_date"].split("-", -1)
    ending = Date.new(array[0].to_i, array[1].to_i, array[2].to_i)
    @orders = Order.where("date > ? and date < ?", start, ending)
    @total_orders = @orders.count
    @page = "Sales"
    render "index"
  end
end

app/views/sales/index.html.erb
<div class = "sales">
  <div class = "dates">
    <h2> Select dates </h2>
      <%= form_with url: fetch_data_path, method: "get" do |form| %>
        <div class = "date-field">
          <%= form.label :starting_date, "Start date:" %>
          <%= form.date_field :starting_date %>
        </div>
        
        <div class = "date-field">
          <%= form.label :ending_date, "End date:" %>
          <%= form.date_field :ending_date %>
        </div>

        <%= form.submit "Done" %>
      <% end %>
  </div>

  <% if @contains_data %>
    <div class = "sales-data">
      <h2> Data </h2>
        
        <% if @total_orders == 0 %>
          <div class = "no-data">
            <p> There are no orders in specified date range </p>
          </div>
        <% else %>
          <div class = "total-orders">
            <p> Total Orders : <%= @total_orders %> </p>
          </div>

          <div class = "orders">
            <table>
              <thead>
                <tr>
                  <th> Order id </th>
                  <% if @current_user.role == "Owner" %>
                    <th> Customer Name </th>
                  <% end %>
                  <th> Ordered on </th>
                  <th> Invoice </th>
                </tr>
              </thead>
              
              <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td> <%= order.id %> </td>
                    <% if @current_user.role == "Owner" %>
                      <td> <%= order.getUserName(order.user_id) %> </td>
                    <% end %>
                    <td> <%=  order.date %></td>

                    <td>
                      <%= form_with url: checkouts_path, method: "get" do |form| %>
                        <%= form.hidden_field :order_id, value: order.id %>
                        <%= form.submit "Invoice", 
                          class: "order-deliver-btn"
                        %>
                      <% end %>
                    </td>

                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </h2>
    </div>
  <% end %>
</div>