config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"
  post "/orders/delivered/:id" => "orders#delivered", as: :order_delivered
  get "/change_menu" => "menus#change_menu", as: :change_menus
  get "/change_menu_items" => "menus#change_menu_items", as: :change_menus_items
  get "/create_all_orders" => "order_items#create_all_orders", as: :create_all_orders
  get "/fetch_data" => "sales#fetch_data", as: :fetch_data
  resources :menu_items, :menus, :orders, :order_items, :checkouts, :cart_items, :sales

  get "/signup" => "users#new", as: :new_users
  post "/signup" => "users#create", as: :users
  
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  get "/confirm" => "orders#confirm", as: :confirm_order
  get "/sessions/update" => "sessions#update", as: :update_session

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candle Cafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
      integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
    <div class = "body">
      <div class = "nav">
        <div class = "main-nav">
          <h2>
            Candle Cafe
          </h2>

          <div class = "body-links">
            <p>
              <%= link_to "Menu", menus_path, method: "get" %>
            </p>

            <% if @current_user.role == "User" %>
              <p>
                <%= link_to "My orders", orders_path, method: "get" %>
              </p>
            <% end %>
            
            <% if @current_user.role == "Owner" %>
              <p>
                <%= link_to "Add user", new_users_path, method: "get" %>
              </p>

              <p>
                <%= link_to "Modify menu", change_menus_path, method: "get" %>
              </p>
              
              <p>
                <%= link_to "Modify menu items", change_menus_items_path, method: "get" %>
              </p>
              
              <p>
                <%= link_to "Sales", sales_path, method: "get" %>
              </p>
            <% end %>
            
            <% if @current_user.role != "User" %>
              <p>
                <%= link_to "All Orders", orders_path, method: "get" %>
              </p>
            <% end %>

            <p>
              <%= link_to "Log out", destroy_session_path, method: "delete" %>
            </p>
          </div>

          <div class = "body-page">
            <% if @page %>
              <p> <%= @page %> </p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
      
      <div class = "main-body">
        <%= yield %>
      </div>
      
    <% if @current_user %>
      </div>
    <% end %>
  </body>
</html>